# Generated by Django 4.2.7 on 2024-03-03 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlist_users',
            field=models.ManyToManyField(blank=True, related_name='listingWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
